<?php
    $this->headLink()->appendStylesheet($this->basePath('css/datatables/css/jquery.dataTables.min.css'));
    $this->headScript()->appendFile($this->basePath('js/datatables/jquery.dataTables.min.js'));
    $this->inlineScript()->appendFile($this->basePath('module/Templates/js/field_types_index.js'));
?>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <span><i class="fa fa-file-text-o"></i> Field Types</span>
            </div>
            <div class="panel-body">
                <a class="btn btn-primary top-button" href="/templates/email_templates/add"><i class="fa fa-plus"></i> Add Field Type</a>
                <?php echo $this->flashMessenger()->render(); ?>
                <table id="form_templates" class="display" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Created By</th>
                            <th>Date Created</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>
