<?php
    $this->headLink()->appendStylesheet($this->basePath('css/datatables/css/jquery.dataTables.min.css'));
    $this->headScript()->appendFile($this->basePath('js/datatables/jquery.dataTables.min.js'));
    $this->inlineScript()->appendFile($this->basePath('module/Templates/js/index.js'));
?>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <span><i class="fa fa-file-text-o"></i> Templates</span>
                <button class="btn btn-primary pull-right"><i class="fa fa-plus"></i> </button>
            </div>
            <div class="panel-body">
                <table id="form_templates" class="display" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Service</th>
                            <th>Description</th>
                            <th>Created By</th>
                            <th>Date Created</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>
