<?php
    $this->headLink()->appendStylesheet($this->basePath('bootstrap-wysiwyg-master/index.css'));
    $this->headLink()->appendStylesheet($this->basePath('bootstrap-wysiwyg-master/external/google-code-prettify/prettify.css'));
    $this->headLink()->appendStylesheet($this->basePath('module/Templates/css/edit.css'));
    $this->headLink()->appendStylesheet($this->basePath('css/bootstrap-responsive.min'));
    $this->headLink()->appendStylesheet($this->basePath('css/bootstrap-combined.no-icons.min'));
    $this->headLink()->appendStylesheet($this->basePath('module/Templates/css/edit.css'));
    $this->headLink()->appendStylesheet($this->basePath('css/select2/select2.min.css'));
    
    
    $this->headScript()->appendFile($this->basePath('bootstrap-wysiwyg-master/bootstrap-wysiwyg.js'));
    $this->headScript()->appendFile($this->basePath('bootstrap-wysiwyg-master/external/google-code-prettify/prettify.js'));
    $this->headScript()->appendFile($this->basePath('bootstrap-wysiwyg-master/external/jquery.hotkeys.js'));
    $this->headScript()->appendFile($this->basePath('js/jquery-ui.js'));
    $this->inlineScript()->appendFile($this->basePath('module/Templates/js/email_templates_edit.js'));
    $this->inlineScript()->appendFile($this->basePath('js/select2/select2.min.js'));
?>

<form action="" method="POST">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <span><i class="fa fa-file-text-o"></i> Email Template</span>
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <div class="row">
                        <div class="col-lg-2">
                            <label for="emailTemplateName">Name:</label>
                        </div>
                        <div class="col-lg-7">
                            <input type="hidden" name="emailTemplateId" id="emailTemplateId" value="<?=isset($this->template['emailTemplateId'])?$this->template['emailTemplateId']:''?>" />
                            <input type="text" class="form-control" id="emailTemplateName" name="emailTemplateName" value="<?=isset($this->post['emailTemplateName'])?$this->post['emailTemplateName']:((isset($this->template['emailTemplateName'])?$this->template['emailTemplateName']:''))?>">
                            <div class="validation_error"><?=isset($this->validation_errors['emailTemplateName'])?$this->validation_errors['emailTemplateName']:''?></div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-lg-2">
                            <label for="emailTemplateMwsId">Status:</label>
                        </div>
                        <div class="col-lg-7">
                            <select id="emailTemplateMwsId" name="emailTemplateMwsId" class="form-control">
                                <?php foreach($this->statuses as $sti => $stv): ?>
                                    <option value="<?=$stv['mwsId']?>" <?=($stv['mwsId'] == (isset($this->post['emailTemplateMwsId'])?$this->post['emailTemplateMwsId']:$this->template['mwsId']))?'selected':''?>><?=$stv['mwsName']?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-lg-2">
                            <label for="emailTemplateContent">Email Content:</label>
                        </div>
                        <div class="col-lg-10">
                            <div id="alerts"></div>
                            <div class="btn-toolbar" data-role="editor-toolbar" data-target="#editor">
                              <div class="btn-group">
                                <a class="btn dropdown-toggle" data-toggle="dropdown" title="Font"><i class="fa fa-font"></i><b class="caret"></b></a>
                                  <ul class="dropdown-menu">
                                  </ul>
                                </div>
                              <div class="btn-group">
                                <a class="btn dropdown-toggle" data-toggle="dropdown" title="Font Size"><i class="fa fa-text-height"></i>&nbsp;<b class="caret"></b></a>
                                  <ul class="dropdown-menu">
                                  <li><a data-edit="fontSize 5"><font size="5">Huge</font></a></li>
                                  <li><a data-edit="fontSize 3"><font size="3">Normal</font></a></li>
                                  <li><a data-edit="fontSize 1"><font size="1">Small</font></a></li>
                                  </ul>
                              </div>
                              <div class="btn-group">
                                <a class="btn" data-edit="bold" title="Bold (Ctrl/Cmd+B)"><i class="fa fa-bold"></i></a>
                                <a class="btn" data-edit="italic" title="Italic (Ctrl/Cmd+I)"><i class="fa fa-italic"></i></a>
                                <a class="btn" data-edit="strikethrough" title="Strikethrough"><i class="fa fa-strikethrough"></i></a>
                                <a class="btn" data-edit="underline" title="Underline (Ctrl/Cmd+U)"><i class="fa fa-underline"></i></a>
                              </div>
                              <div class="btn-group">
                                <a class="btn" data-edit="insertunorderedlist" title="Bullet list"><i class="fa fa-list-ul"></i></a>
                                <a class="btn" data-edit="insertorderedlist" title="Number list"><i class="fa fa-list-ol"></i></a>
                                <a class="btn" data-edit="outdent" title="Reduce indent (Shift+Tab)"><i class="fa fa-indent-left"></i></a>
                                <a class="btn" data-edit="indent" title="Indent (Tab)"><i class="fa fa-indent-right"></i></a>
                              </div>
                              <div class="btn-group">
                                <a class="btn" data-edit="justifyleft" title="Align Left (Ctrl/Cmd+L)"><i class="fa fa-align-left"></i></a>
                                <a class="btn" data-edit="justifycenter" title="Center (Ctrl/Cmd+E)"><i class="fa fa-align-center"></i></a>
                                <a class="btn" data-edit="justifyright" title="Align Right (Ctrl/Cmd+R)"><i class="fa fa-align-right"></i></a>
                                <a class="btn" data-edit="justifyfull" title="Justify (Ctrl/Cmd+J)"><i class="fa fa-align-justify"></i></a>
                              </div>
                              <div class="btn-group">
                                          <a class="btn dropdown-toggle" data-toggle="dropdown" title="Hyperlink"><i class="fa fa-link"></i></a>
                                            <div class="dropdown-menu input-append">
                                                    <input class="span2" placeholder="URL" type="text" data-edit="createLink"/>
                                                    <button class="btn" type="button">Add</button>
                                </div>
                                <a class="btn" data-edit="unlink" title="Remove Hyperlink"><i class="fa fa-cut"></i></a>

                              </div>

                              <div class="btn-group">
                                <a class="btn" title="Insert picture (or just drag & drop)" id="pictureBtn"><i class="fa fa-picture"></i></a>
                                <input type="file" data-role="magic-overlay" data-target="#pictureBtn" data-edit="insertImage" />
                              </div>
                              <div class="btn-group">
                                <a class="btn" data-edit="undo" title="Undo (Ctrl/Cmd+Z)"><i class="fa fa-undo"></i></a>
                                <a class="btn" data-edit="redo" title="Redo (Ctrl/Cmd+Y)"><i class="fa fa-repeat"></i></a>
                              </div>
                              <input type="text" data-edit="inserttext" id="voiceBtn" x-webkit-speech="">
                            </div>

                            <div id="editor" class="droppable">
                                <?= isset($this->post['emailTemplateContent']) ? $this->post['emailTemplateContent'] : html_entity_decode(HTMLENTITIES($this->template['emailTemplateContent']))?>
                            </div>
                            <input type="hidden" name="emailTemplateContent" id="emailTemplateContent" value="<?=html_entity_decode(HTMLENTITIES($this->template['emailTemplateContent']))?>"/>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                <button type="submit" class="btn btn-info">Update</button>
                <a href="/templates/email_templates" class="btn btn-default">Back</a>
            </div>
        </div>
    </div>
</form>